### ISSUE TITLE
manifest path is wrong for releasing via Release-Support

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/VisualSoar#1]
build.xml must be changed like so in order for the jar to work in the final release:

    <property name="manifest.classpath" value="java/sml.jar" />

Note that this does not work for development, where `sml.jar` is located in `lib/`. For the debugger build, we have a separate manifest for development and release. We should probably do a similar thing here.

Note also that the `manifest.classpath` is given twice in the build. I just remove one and fix the other.

**Comment by amnuxoll** [comment]
This was repaired in commit 
https://github.com/SoarGroup/VisualSoar/commit/6887c96c55c3ffe7b0510937a045e5bfba801bdf
