### ISSUE TITLE
Popup windows on wrong screen

### ISSUE THREAD

**Issue by PLatCIC** [SoarGroup/VisualSoar#12]
When working on a system with multiple screens, popup windows are not shown on the same screen as the main window. For instances, when creating the data map from existing operators, a popup with confirmation pops up, but on a whole different screen. This popup may not be obvious to the user, so it appears that VS has frozen since you can't do anything with it until the popup is closed.

**Comment by johnlaird** [comment]
Could you be more specific? I assume this is Windows. Which screen is VS running in (primary or secondary)? Can you also specify what you mean by "creating a data map from existing operators"  - are you copying, linking, ???  The datamap for an operator should be initialized (with the name) when you create the operator from the left-hand window.
(I've never seen this on my two-screen system where VS is on the main screen under Windows).

**Comment by PLatCIC** [comment]
I am on Windows and VS is on a secondary screen, but the popups always appear on the primary screen. What I mean is clicking on the Datamap->Generate the Datamap from the Current Operator Hierarchy button.

**Comment by amnuxoll** [comment]
This is mostly fixed in this commit:  https://github.com/SoarGroup/VisualSoar/commit/4bb8d274896cbd22a25daa598713421d7757255f

The file chooser dialog is still not behaving but it can't be fixed easily since it's a custom dialog rather than the one provided by the system.  See MainFrame.ghettoFileChooser()
