### ISSUE TITLE
ability to change a project opened as read-only

### ISSUE THREAD

**Issue by scijones** [SoarGroup/VisualSoar#14]
I opened a project (read only).

I then clicked "Datamap" and "generate the datamap from the current operator hierarchy".

Then, I opened the datamap and clicked "validation" and "validate datamap".

Then, I closed the project.

There were changes in datamap files within the project.

**Comment by amnuxoll** [comment]
This was added in this commit:  https://github.com/SoarGroup/VisualSoar/commit/b93b59b471b828db7510d2b8cd826d2053850023
