### ISSUE TITLE
"browse" within new project window doesn't work

### ISSUE THREAD

**Issue by scijones** [SoarGroup/VisualSoar#15]
On John's machine and on mine, it doesn't seem to do anything.

**Comment by amnuxoll** [comment]
I'm not able to recreate this on Linux or Windows.  I can browse to a folder.  If I've overlooked something please reopen this bug and provide steps to recreate.
![image](https://github.com/SoarGroup/VisualSoar/assets/6465381/4f1771e0-1fea-45b2-b056-15a328c6d464)

**Comment by scijones** [comment]
I may have an older version of visualsoar (4.6.17w from 17 Mar), but on mine the steps are

1. open visualsoar
2. click file
3. click new project
4. click browse

The button seems to depress, but does not visually appear to return to a "non-clicked" state on my release of the click. I move the mouse and it appears to unclick, but regardless, nothing happens.

HOWEVER, I will make sure I have the latest and then retest.

**Comment by scijones** [comment]
I guess this is what you want?

from java --version (in powershell)

> java 21.0.2 2024-01-16 LTS
> Java(TM) SE Runtime Environment (build 21.0.2+13-LTS-58)
> Java HotSpot(TM) 64-Bit Server VM (build 21.0.2+13-LTS-58, mixed mode, sharing)

and

Windows 11 home

**Comment by amnuxoll** [comment]
I believe I've found and fixed this bug with this commit.   Thanks for John for his insight on this one.  https://github.com/SoarGroup/VisualSoar/commit/9515ec8ecbda89b7f25fd22f899a690d4610a680
