### ISSUE TITLE
Might be issue in renaming an operator with suboperators. 

### ISSUE THREAD

**Issue by johnlaird** [SoarGroup/VisualSoar#17]

**Comment by amnuxoll** [comment]
I think I've been able to recreate this.  I'm getting some strange error popups when I do this.
![image](https://github.com/SoarGroup/VisualSoar/assets/6465381/076582df-ee24-4a75-9c51-11f7f592352a)
![image](https://github.com/SoarGroup/VisualSoar/assets/6465381/de40e24f-d207-472e-98f7-bf009bb109fd)

**Comment by amnuxoll** [comment]
I believe I have repaired this issue.  See this commit:  https://github.com/SoarGroup/VisualSoar/commit/94babdbadbd478e628cb5a2d2532d25b810567a3
