### ISSUE TITLE
Saved project can't be opened

### ISSUE THREAD

**Issue by PLatCIC** [SoarGroup/VisualSoar#20]
I created a new project from scratch in VisualSoar 4.6.16. Then I added a bunch of code to the initialize operator to create a deep data structure. (The initialize-test-1.soar file is attached with its extension changed to .txt so GitHub will accept it.) Then I clicked on the Generate Datamap Entries for this file a number of times. Each time it added more depth to the datamap. When it finally wouldn't add any more, I saved the project and closed VisualSoar, with tabs open for both the top state datamap and the initialize operator.

When I tried to open the project again, I got this error and could never recover the project:

![Bad File error](https://github.com/SoarGroup/VisualSoar/assets/107441581/f24afd14-37a7-4ef6-90cd-583e12da0143)

[initialize-test-1.txt](https://github.com/SoarGroup/VisualSoar/files/14877288/initialize-test-1.txt)

**Comment by PLatCIC** [comment]
Today I had another instance of this bug. I have been working on an agent called base-station-test for a while, and making a number of changes to it, all with VisualSoar. I've been through several cycles of this with no serious problems. There have been some strange things, though. When I have VS build a datamap automatically, I end up with two versions of the recieve-pong [sic] operator, one of which only has the name of the operator and the other has a bunch of structure.

Well today I opened the project again, uncommented and made some other changes to the user-command operator, saved the project, and closed VS. A few minutes later I tried to open the project again and got that same nasty error. I have no idea how to work around it, so I'll have to continue working on this agent without VS, which is sad.

I copied all the files for just this agent into a separate folder and tried to open the project. I got the same error. A .zip file of that folder is attached.

[base-station agent.zip](https://github.com/SoarGroup/VisualSoar/files/14951487/base-station.agent.zip)

**Comment by amnuxoll** [comment]
I've repaired this particular bug here:  https://github.com/SoarGroup/VisualSoar/commit/54f41d1ed55b9e06d8b9a01b156a5cd3dea0adfc

**Comment by PLatCIC** [comment]
I just had this happen again. I look forward to getting the version with this fixed.

**Comment by PLatCIC** [comment]
This has happened to me several times on the same small project. I rebuilt the project from scratch, adding in the code I had before from a copy I had saved, and saved the project. It opened OK. Then I opened it again and selected the comprehend-sentence operator and clicked on Generate Datamap Entries for this File. It generated a bunch of new things in the datamap. Then I saved and closed the project. When I tried to open it again I got the nasty error message as shown above. It seems clear that something bad happens when generating the datamap using the tool in Visual Soar. The bad file has to be the .dm file, because if I replace with a copy I saved before clicking on Generate Datamap, then it opens fine.

[language.zip](https://github.com/SoarGroup/VisualSoar/files/15267676/language.zip)

This .zip file has the whole project in the form where it opens OK. If you open it, do Generate Datamap on the whole thing or on just comprehend-sentence, then the .dm file is corrupted and the project won't open.

I feel this is a pretty high priority bug.

**Comment by amnuxoll** [comment]
It sounds like a serious bug to me as well.  Please, report this as a new issue rather than inserting it here as I may lose track of it if you do not.  Also, please make sure JEL knows about this and can confirm I should add it to my to-do list.

Thank you very much for providing the .zip and the steps to recreate.  That will make this bug easy to solve.

**Comment by PLatCIC** [comment]
This is exactly the same issue as above, so let's keep it in the same place. John, do you think this should be on Andy's to do list?

**Comment by amnuxoll** [comment]
If you're sure it's exactly the same issue then I have already fixed it.  It will be in the next release.

**Comment by PLatCIC** [comment]
That sounds good. It might be good to test it on the project I sent before you release.

**Comment by PLatCIC** [comment]
I tested this again with version 4.6.20, and it appears this bug has indeed been fixed.
