### ISSUE TITLE
project files change without user action

### ISSUE THREAD

**Issue by garfieldnate** [SoarGroup/VisualSoar#7]
From @PLindes: if you just open a VisualSoar project, the project files are often changed even when the user has not edited the datamap or any code yet.

This is confusing and worrying for users; who do you know when files are changed in a significant way? How do you know when you should commit? Do the changes cause change in functionality?

I bet there's some part of the code that just reads and immediately writes out the files again, with non-deterministic ordering due to using a HashMap or similar under the hood.

**Comment by johnlaird** [comment]
I believe this was fixed in 4.6.11
